Vagrant.configure("2") do |config|
  
  # Kafka broker 1
  config.vm.define "broker1" do |b1|
    b1.vm.box = "ubuntu/focal64"
    b1.vm.hostname = "broker1"
    b1.vm.network "private_network", ip: "192.168.33.10"
    b1.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
    b1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y default-jre
      wget https://downloads.apache.org/kafka/3.4.0/kafka_2.13-3.4.0.tgz
      tar -zxf kafka_2.13-3.4.0.tgz
	  cd kafka_2.13-3.4.0
	  ./bin/kafka-server-start.sh ./config/server.properties --override listeners=PLAINTEXT://192.168.33.10:9092 --override broker.id=1 --override zookeeper.connect=192.168.33.1:2181 
    SHELL
  end
# Kafka broker 2
  config.vm.define "broker2" do |b2|
    b2.vm.box = "ubuntu/focal64"
    b2.vm.hostname = "broker2"
    b2.vm.network "private_network", ip: "192.168.33.11"
    b2.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
    b2.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y default-jre
      wget https://downloads.apache.org/kafka/3.4.0/kafka_2.13-3.4.0.tgz
      tar -zxf kafka_2.13-3.4.0.tgz
	  cd kafka_2.13-3.4.0
	  ./bin/kafka-server-start.sh ./config/server.properties --override listeners=PLAINTEXT://192.168.33.11:9093 --override broker.id=2 --override zookeeper.connect=192.168.33.1:2181 
    SHELL
  end
end

